---
app:
  metadata: gitops-argocd-1.0.1
  replicas: 1
  envs:
    POSTGRES_URL: jdbc:postgresql://demo-db:5432/demo_database
  postgresql:
    auth:
      database: demo_database
      password: supersecret
      username: user
    primary:
      containerSecurityContext:
        enabled: false
        runAsUser: auto
      podSecurityContext:
        enabled: false
        fsGroup: auto
    securityContext:
      enabled: false
    shmVolume:
      chmod:
        enabled: false
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: auto
