---
app:
  envs:
    POSTGRES_PASSWORD: supersecret
    POSTGRES_URL: jdbc:postgresql://demo-db:5432/demo_database
    POSTGRES_USERNAME: user
  image: quay.io/shani1/gitops-argocd:1.0.1
  metadata: gitops-argocd-1.0.1
  ports:
    http: 8080
  postgresql:
    auth:
      database: demo_database
      password: supersecret
      username: user
    primary:
      containerSecurityContext:
        enabled: false
        runAsUser: auto
      podSecurityContext:
        enabled: false
        fsGroup: auto
    securityContext:
      enabled: false
    shmVolume:
      chmod:
        enabled: false
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: auto
  replicas: 1
