---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/zeeshan-tufail/gitops-argocd.git
    app.quarkus.io/quarkus-version: 3.15.4.redhat-00001
    app.quarkus.io/commit-id: d09583a1ed16e7d1e21888231923daa83bfccc31
    app.quarkus.io/vcs-uri: https://github.com/zeeshan-tufail/gitops-argocd.git
    app.quarkus.io/build-timestamp: 2025-04-19 - 11:23:08 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/version: 1.0.1
    app.kubernetes.io/name: gitops-argocd
  name: gitops-argocd
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.1
      app.kubernetes.io/name: gitops-argocd
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.openshift.io/vcs-uri: https://github.com/zeeshan-tufail/gitops-argocd.git
        app.quarkus.io/quarkus-version: 3.15.4.redhat-00001
        app.quarkus.io/commit-id: d09583a1ed16e7d1e21888231923daa83bfccc31
        app.quarkus.io/vcs-uri: https://github.com/zeeshan-tufail/gitops-argocd.git
        app.quarkus.io/build-timestamp: 2025-04-19 - 11:23:08 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/version: 1.0.1
        app.kubernetes.io/name: gitops-argocd
    spec:
      containers:
        - env:
            - name: POSTGRES_URL
              value: {{ .Values.app.envs.POSTGRES_URL | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.app.envs.POSTGRES_PASSWORD | quote }}
            - name: POSTGRES_USERNAME
              value: {{ .Values.app.envs.POSTGRES_USERNAME | quote }}
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          name: gitops-argocd
          ports:
            - containerPort: {{ .Values.app.ports.http }}
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
              cpu: "0.01"
              memory: 128Mi
      serviceAccountName: gitops-argocd
