---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.15.4.redhat-00001
    app.quarkus.io/build-timestamp: 2025-04-12 - 06:50:03 +0000
  labels:
    app.kubernetes.io/name: gitops-argocd
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: gitops-argocd
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: gitops-argocd
