---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.15.4.redhat-00001
    app.quarkus.io/build-timestamp: 2025-04-12 - 06:50:03 +0000
  labels:
    app.kubernetes.io/name: gitops-argocd
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
  name: gitops-argocd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: gitops-argocd
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
